modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="ifoe_bravers"
version="${file.jarVersion}"
displayName="IfOE_Bravers"
description='''
Inherit from Outer Epic - 異世界の英雄の力を継承するMOD
'''
authors="MayvisScarlet"
credits="Apotheosis MOD"
logoFile="logo.png"

[[dependencies.ifoe_bravers]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.ifoe_bravers]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

# Origins関連は任意依存として設定（開発時の競合回避）
[[dependencies.ifoe_bravers]]
modId="origins"
mandatory=false
versionRange="[1.10.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.ifoe_bravers]]
modId="apotheosis"
mandatory=false
versionRange="[7.4.0,)"
ordering="AFTER"
side="BOTH"